### ISSUE TITLE
Roadmap to PSL Acceptance

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/taxdata#292]
This issue aims to create a checklist and roadmap for bringing TaxData into compliance with the criteria for acceptance into the Policy Simulation Library. I've broken the checklist down into sections based on the three kinds of criteria listed [here](https://github.com/open-source-economics/PSL/blob/master/Criteria/library_criteria.md).

## Acceptance Criteria

- [x] Add a descriptive list of all undisclosed data
This only relates to the PUF because the CPS file is publicly available. It would be simple to add a file containing descriptive statistics for the statistically matched PUF produced by the scripts in this repo.
- [x] Add a suggested citation
This is relatively straightforward. Once we move to a versioning system we can adopt the citation preferences of related projects like Tax-Calculator
- [x] Installation directions
These will mostly be related to forking the repo and installing the `taxdata-dev` environment.
- [x] Adopt a versioning scheme
Although this project will not be released as a package on the Anaconda distribution, I believe that a semantic versioning system would be appropriate. Adopting a versioning system has been discussed before in this project, but never followed through on because the Tax-Calculator change-log and versions have been sufficient. This is no longer the case if TaxData is to join PSL.

## Community Criteria
- [ ] Create a public roadmap
- [x] Create a more substantial contributor guide
We have various documents on how to update data and how to run the file creation scripts, but given past experiences trying to onboard new contributors I believe these can be made significantly better.
- [ ] Setting regular office hours/standing meetings
As of now the TaxData standing meetings have been lumped in with the Tax-Calculator developer and standing meetings. This practice could be continued or we could adopt separate meetings depending on the needs of the community.
- [x] Including a disclosure
This can be copied from the Tax-Calculator repository
- [x] Maintain a change-log
This will be easier when we adopt a consistent versioning system. 

## Interoperability Criteria
- [x] Source code should be written in an open source language
The only code written in a non-open-source we have in the repo are the massive SAS scripts used to create the CPS file. I had been working on re-writing this code in Python, but that work has taken a backseat to working on creating a synthetic PUF that could potentially make the CPS file obsolete.
- [ ] Construct a `PSL_Catalog.json` file.

cc @MattHJensen @martinholmer @Amy-Xu

**Comment by andersonfrailey** [comment]
TaxData has been accepted into PSL so closing this issue.
